# Generated by Django 3.2 on 2022-12-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rank',
            new_name='role',
        ),
    ]
