# Generated by Django 3.2 on 2022-12-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_titlegenre_genre'),
        ('reviews', '0003_auto_20221214_2110'),
    ]

    operations = [
    ]
