# Generated by Django 3.2 on 2022-12-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='reviews.category'),
        ),
        migrations.AlterField(
            model_name='titlegenre',
            name='genre',
            field=models.ForeignKey(db_column='genre_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.genre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='titlegenre',
            name='title',
            field=models.ForeignKey(db_column='title_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.title'),
        ),
    ]
