# Generated by Django 3.2 on 2022-12-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20221217_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titlegenre',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='titlegenre',
            old_name='title',
            new_name='title_id',
        ),
    ]
