# Generated by Django 3.2 on 2022-12-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_review_unique_title_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(verbose_name=range(1, 10)),
        ),
    ]
