# Generated by Django 3.2 on 2022-12-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
